catalog/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views


book_patterns = [
    path('', views.BookListView.as_view(), name='books-list'),
    path('new', views.BookCreate.as_view(), name='book-new'),
    path('edit/<int:pk>', views.BookUpdate.as_view(), name='book-edit'),
    path('<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('delete/<int:pk>', views.BookDelete.as_view(), name='book-delete'),
 
]

languaje_patterns = [
    path('', views.LanguajeListView.as_view(), name='lan_list'),
    path('new', views.LanguajeCreate.as_view(), name='lan_create'),
    path('edit/<int:pk>', views.LanguajeUpdate.as_view(), name='lan_edit'),
    path('delete/<int:pk>', views.LanguajeDelete.as_view(), name='lan_delete'),
 
]
genre_patterns = [
    path('', views.GenreListView.as_view(), name='gen_list'),
    path('new', views.GenreCreate.as_view(), name='gen_create'),
    path('edit/<int:pk>', views.GenreUpdate.as_view(), name='gen_edit'),
    path('delete/<int:pk>', views.GenreDelete.as_view(), name='gen_delete'),
]

authors_patterns = [
    path('', views.AuthorListView.as_view(), name='author_list'),
    path('new', views.AuthorCreate.as_view(), name='author_new'),
    path('edit/<int:pk>', views.AuthorUpdate.as_view(), name='author_edit'),
    path('<int:pk>', views.AuthorDetailView.as_view(), name='author_detail'),
    path('delete/<int:pk>', views.AuthorDelete.as_view(), name='author_delete'),
]
bookinstance_patterns = [
    path('', views.BookInstanceListView.as_view(), name='bookinstance_list'),
    path('new', views.BookInstanceCreate.as_view(), name='bookinstance_new'),
    path('edit/<slug:id>', views.BookInstanceUpdate.as_view(), name='bookinstance_edit'),
    path('<slug:id>', views.BookInstanceDetailView.as_view(), name='bookinstance_detail'),
]

urlpatterns = [
    path('', views.index, name='index'),
    path('book/', include(book_patterns)),
    path('author/', include(authors_patterns)),
    path('genre/', include(genre_patterns)),
    path('languaje/', include(languaje_patterns)),
    path('bookinstance/', include(bookinstance_patterns)),

    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    
    # path('book/intance/', include(bookintance_patterns)),
]

proyecto/urls.py
from django.urls import include
from django.contrib import admin
from django.urls import path
from catalog import views

urlpatterns = [
    # path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('catalog/', include('catalog.urls')),
]

from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
# users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('', ListUserView.as_view(), name='users'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('<int:pk>/', UpdateUserView.as_view(), name='users_edit'),
]

catalog/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User
from django.urls import reverse 
from django.db import models
from datetime import date
from proyecto import settings
import uuid

class Genre(models.Model):
    name = models.CharField(max_length=200, help_text="Ingrese el nombre del género (p. ej. Ciencia Ficción, Poesía Francesa etc.)")
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('genre_detail', args=[str(self.id)])

class Languaje(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=200)

    author = models.ForeignKey('Author', on_delete=models.CASCADE)
    summary = models.TextField(max_length=1000, help_text="Ingrese una breve descripción del libro")
    isbn = models.CharField('ISBN',max_length=13, help_text='13 Number Caracteres')
    genre = models.ManyToManyField(Genre, help_text="Seleccione un genero para este libro")
    languaje = models.ManyToManyField(Languaje, help_text="Ingrese idioma(s) del libro")
    photo = models.ImageField(upload_to='images/', blank=True, null=True)
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])     

    def display_genre(self):
        return ', '.join([ genre.name for genre in self.genre.all()[:3] ])
    display_genre.short_description = 'Genre'

    def individual_gen(self):
        ret = ''
        for gen in self.genre.all():
            ret = ret + gen.name + ','
        return ret[:-1]
    
    @property
    def imageURL(self):
        try:
            url = self.photo.url
        except:
            url = ''
        return url

class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,editable=False, help_text="ID único para este libro particular en toda la biblioteca")
    book = models.ForeignKey('Book', on_delete=models.CASCADE) 
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True, help_text="YYYY-MM-DD")
    borrower = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Disponibilidad del libro')

    class Meta:
        ordering = ["due_back"]
        permissions = (
            ("can_mark_returned", "Set book as returned"),
            )  
    
    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False
        

    def __str__(self):
        return '%s (%s)' % (self.id,self.book.title)

    # def get_absolute_url(self):
    #     return reverse ('booki-detail', args=[str(self.id)])

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)
    
    def get_absolute_url(self):
        return reverse('author_detail', args=[str(self.id)])
    

    def __str__(self):
        return '%s, %s' % (self.last_name, self.first_name)

catalog/forms.py
from django.forms import ModelForm
from .models import *

class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = '__all__'

catalog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import render
from django.contrib import messages
from django.views import generic
from .models import *
from .forms import *

@login_required
def index(request):
    template = "catalog/index.html" 
    num_books=Book.objects.all().count()
    num_instances=BookInstance.objects.all().count()
    num_instances_available=BookInstance.objects.filter(status__exact='a').count()
    num_authors=Author.objects.count()

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    ctx = {
        'num_books' :num_books,
        'num_instances':num_instances,
        'num_instances_available':num_instances_available,
        'num_authors':num_authors,
        'num_visits': num_visits,
    }
    return render(request, template, ctx)

""" BOOK """
class BookListView(LoginRequiredMixin,generic.ListView):
    model = Book
    queryset = Book.objects.all()
    paginate_by = 10

class BookDetailView(LoginRequiredMixin,generic.DetailView):
    model = Book
    queryset = Book.objects.all()
    template_name = 'catalog/book_detail.html'
    
class BookCreate(PermissionRequiredMixin,generic.CreateView):
    permission_required = 'catalog.add_book'
    model = Book
    form_class = BookForm
    success_url = reverse_lazy('books-list')
    template_name = 'catalog/book_create.html'

class BookUpdate(PermissionRequiredMixin,generic.UpdateView):
    permission_required = 'catalog.change_book'
    model = Book
    fields = ['title', 'author', 'summary', 'isbn', 'genre', 'languaje','photo']
    success_url = reverse_lazy('books-list')

class BookDelete(PermissionRequiredMixin,generic.DeleteView):
    permission_required = ('catalog.add_book','catalog.delete_book')
    model = Book
    success_url = reverse_lazy('books-list')


""" BOOK INSTANCE """
class LoanedBooksByUserListView(LoginRequiredMixin,generic.ListView):
    # permission_required = ('catalog.can_mark_returned', 'catalog.can_edit')
    model = BookInstance
    template_name ='catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10
    
    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')


""" AUTHOR """
class AuthorListView(LoginRequiredMixin,generic.ListView):
    model = Author
    queryset = Author.objects.all()
    paginate_by = 5

class AuthorDetailView(LoginRequiredMixin,generic.DetailView):
    model = Author
    queryset = Author.objects.all()
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['book_list'] = Book.objects.all()
        return context
class AuthorCreate(PermissionRequiredMixin,generic.CreateView):
    permission_required = 'catalog.add_author'
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']    
    success_url = reverse_lazy('author_list')
    template_name = 'catalog/author_create.html'

class AuthorUpdate(PermissionRequiredMixin,generic.UpdateView):
    permission_required = 'catalog.change_author'
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']    
    success_url = reverse_lazy('author_list')

class AuthorDelete(PermissionRequiredMixin,generic.DeleteView):
    permission_required = 'catalog.delete_author'
    model = Author
    success_url = reverse_lazy('author_list')

""" Languaje """
class LanguajeListView(LoginRequiredMixin,generic.ListView):
    model = Languaje
    queryset = Languaje.objects.all()

class LanguajeCreate(PermissionRequiredMixin,generic.CreateView):
    permission_required = 'catalog.add_languaje'
    model = Languaje
    fields = ['name']    
    success_url = reverse_lazy('lan_list')

class LanguajeUpdate(PermissionRequiredMixin,generic.UpdateView):
    permission_required = 'catalog.change_languaje'
    model = Languaje
    fields = ['name']    
    success_url = reverse_lazy('lan_list')

class LanguajeDelete(PermissionRequiredMixin,generic.DeleteView):
    permission_required = 'catalog.delete_languaje'
    model = Languaje
    success_url = reverse_lazy('lan_list')

""" GENRE """

class GenreListView(LoginRequiredMixin,generic.ListView):
    model = Genre
    queryset = Genre.objects.all()

class GenreCreate(PermissionRequiredMixin,generic.CreateView):
    permission_required = 'catalog.add.genre'
    model = Genre
    fields = ['name']    
    success_url = reverse_lazy('gen_list')
    template_name = 'catalog/genre_create.html'

class GenreUpdate(PermissionRequiredMixin,generic.UpdateView):
    permission_required = 'catalog.change_genre'
    model = Genre
    fields = ['name']    
    success_url = reverse_lazy('gen_list')

class GenreDelete(PermissionRequiredMixin,generic.DeleteView):
    permission_required = 'catalog.delete_genre'
    model = Genre
    success_url = reverse_lazy('gen_list')

""" Intance """
class BookInstanceListView(LoginRequiredMixin,generic.ListView):
    model = BookInstance
    queryset = BookInstance.objects.all()

class BookInstanceDetailView(LoginRequiredMixin,generic.DetailView):
    model = BookInstance
    queryset = BookInstance.objects.all()
    
class BookInstanceCreate(PermissionRequiredMixin,generic.CreateView):
    permission_required = 'catalog.add.bookinstance'
    model = BookInstance
    fields = ['book', 'imprint', 'due_back', 'borrower', 'status']    
    success_url = reverse_lazy('bookinstance_list')
    template_name = 'catalog/bookinstance_create.html'

class BookInstanceUpdate(PermissionRequiredMixin,generic.UpdateView):
    permission_required = 'catalog.change_bookinstance'
    model = BookInstance
    
    fields = ['book','imprint','due_back','borrower','status']    
    success_url = reverse_lazy('bookinstance_list')

catalog/templates/catalog/author_confirm_delete.html
{% extends "catalog/main.html" %}
{% load bootstrap4 %}


{% block breadcrums %}
<li class="breadcrumb-item"><a href="{% url 'author_list' %}">Eliminar</a></li>
<li class="breadcrumb-item"><a href="{% url 'author_detail' author.pk %}">{{ author.first_name }}</a></li>
<li class="breadcrumb-item">Eliminar Autor</li>
{% endblock breadcrums %} 
    

{% block content %}
<div class="container">
<h1>Author Delete</h1>
<form method="post">
    {% csrf_token %}
    <p>¿Estas seguro de eliminar a <strong>"{{ object }}"</strong>?</p>
    
    <button type="submit" class="btn btn-danger" ><i class="fas fa-trash-alt"></i> Eliminar</button>
    
    <a href="{% url 'author_detail' author.pk %}" class="btn btn-light">Cancelar</a> 
</form>

</div>
{% endblock %}

catalog/templates/catalog/author_create.html
{% extends 'catalog/main.html' %}
{% load bootstrap4 %}


{% block breadcrums %}
<li class="breadcrumb-item"><a href="{% url 'author_list' %}">Listado de Autores</a></li>
<li class="breadcrumb-item">Agregar Autor </li>
{% endblock breadcrums %}
    
{% block content %}
<div class="container">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <!-- {{ form.as_p }} -->
        <button type="submit" class="btn btn-primary" ><i class="fas fa-trash-alt"></i> Enviar</button>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/author_form.html
{% extends 'catalog/main.html' %}
{% load bootstrap4 %}


{% block breadcrums %}
<li class="breadcrumb-item"><a href="{% url 'author_list' %}">autores</a></li>
<li class="breadcrumb-item"><a href="{% url 'author_detail' author.pk %}">{{ author.first_name }}</a></li>
<li class="breadcrumb-item">Editar </li>
{% endblock breadcrums %}
    
{% block content %}
<div class="container">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <!-- {{ form.as_p }} -->
        <button type="submit" class="btn btn-primary" ><i class="fas fa-trash-alt"></i> Enviar</button>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "catalog/main.html" %}

{% block breadcrums %}
<li class="breadcrumb-item">Listado de autores</li>
{% endblock breadcrums %} 


{% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-10 col-md-8 col-sm-12 text-center" ><h1>Listado de Autores</h1>
    </div>
    {% if perms.catalog.add_author %}
    <div class="col-lg-2 col-md-4 col-sm-12 mb-2 text-center">
      <a href="{% url 'author_new' %}">
      <button type="button" class="btn btn-success">Agregar Autor</button>
      </a>
    </div>
    {% endif %}
  </div>

<div class="container">
    {% if author_list %}
  
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Nombre</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          {% for author in author_list %}
          <tr>
            <td><a href="{{ author.get_absolute_url }}">{{ author.first_name}} {{author.last_name}}</a></td>
            <td>
              <div class="row">
                <div class="col-lg-8 col-md-6 col-sm-12" ></div>
                 <div class="col-lg-4 col-md-6 col-sm-12 text-center">
                  <a href="{% url 'author_detail' author.pk %}">
                    <button type="button" class="btn btn-dark">Detalle</button>
                  </a>
                </div>
              </div>
          </tr>
          {% endfor %}
        </tbody>
      </table>


    {% else %}
      <p>no hay.</p>
    {% endif %}       
  </div>
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "catalog/main.html" %}
{% load static %}
<!-- breadcrums -->
{% block breadcrums %}
<li class="breadcrumb-item"><a href="{% url 'books-list' %}">Listado de libros</a></li>
<li class="breadcrumb-item">{{ book.title }}</li>
{% endblock breadcrums %} 



{% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-4 col-md-6 col-sm-12">
      <img src="{{book.imageURL}}" class="img-thumbnail" alt="img" >  
    </div>
    
    <div class="col-lg-8 col-md-6 col-sm-12">
      <h2>{{ book.title }}</h1>
      <p><strong>Summary:</strong> {{ book.summary }}</p>
      <p><strong>Author:</strong> <a href="{% url 'author_detail' book.author.pk %}">{{ book.author }}</a></p>
      <p><strong>Language:</strong> {{ book.language }}</p>  
      <p><strong>ISBN:</strong> {{ book.isbn }}</p> 
      <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  
    </div>
  </div>
  <div class="row">
    <div class="col-lg-8 col-md-6 col-sm-12" ></div>
    <div class="col-lg-4 col-md-6 col-sm-12 text-center">
      {% if perms.catalog.change_book %}
      <a href="{% url 'book-edit' book.pk %}">
        <button type="button" class="btn btn-success">Editar</button>
      </a>
      {% endif %}
      {% if perms.catalog.delete_book%}
      <a href="{% url 'book-delete' book.pk %}">
        <button type="button" class="btn btn-danger">Eliminar</button>
      </a>
      {% endif %}
    </div>
  </div>
    
    <div style="margin-left:20px;margin-top:20px">
      <h4>Copies</h4>
      
      {% for copy in book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
      {% if copy.status != 'a' %}<p><strong>Fecha de devolución:</strong> {{copy.due_back}}</p>{% endif %}
      <p><strong>Copia:</strong> {{copy.imprint}}</p>
      <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
      {% endfor %}
    </div>
</div>
{% endblock %}

catalog/templates/catalog/book_form.html
{% extends 'catalog/main.html' %}
{% load bootstrap4 %}


{% block breadcrums %}
<li class="breadcrumb-item"><a href="{% url 'books-list' %}">Listado de libros</a></li>
<li class="breadcrumb-item"><a href="{% url 'book-detail' book.pk %}">{{ book.title }}</a></li>
<li class="breadcrumb-item">Editar </li>
{% endblock breadcrums %}
    
{% block content %}
<div class="container">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <!-- {{ form.as_p }} -->
        <button type="submit" class="btn btn-primary" ><i class="fas fa-trash-alt"></i> Enviar</button>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/bookinstance_detail.html
{% extends "catalog/main.html" %}
{% load static %}
<!-- breadcrums -->
{% block breadcrums %}
<li class="breadcrumb-item"><a href="{% url 'bookinstance_list' %}">Listado de libros</a></li>
<li class="breadcrumb-item">{{ bookinstance.title }}</li>
{% endblock breadcrums %} 



{% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-4 col-md-6 col-sm-12">
    </div>
    
    <div class="col-lg-8 col-md-6 col-sm-12">
      <h2>{{ bookinstance.book.title }}</h1>
      <p><strong>Summary:</strong> {{ bookinstance.book.summary }}</p>
      <p><strong>Author:</strong> <a href="{% url 'bookinstanceinstance_detail' bookinstance.book.author %}">{{ bookinstance.book.author }}</a></p>
      <p><strong>Language:</strong> {{ bookinstance.book.language }}</p>  
      <p><strong>ISBN:</strong> {{ bookinstance.book.isbn }}</p> 
    </div>
  </div>
  <div class="row">
    <div class="col-lg-8 col-md-6 col-sm-12" ></div>
    <div class="col-lg-4 col-md-6 col-sm-12 text-center">
      {% if perms.catalog.change_bookinstance %}
      <a href="#">
        <button type="button" class="btn btn-success">Editar</button>
      </a>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

catalog/templates/catalog/bookinstance_form.html
{% extends 'catalog/main.html' %}
{% load bootstrap4 %}


{% block breadcrums %}
<li class="breadcrumb-item"><a href="{% url 'bookinstance_list' %}">Listado de lenguajes</a></li>
<li class="breadcrumb-item">Editar </li>
{% endblock breadcrums %}
    
{% block content %}
<div class="container">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <!-- {{ form.as_p }} -->
        <button type="submit" class="btn btn-primary" >Enviar</button>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/genre_confirm_delete.html
{% extends "catalog/main.html" %}
{% load bootstrap4 %}


{% block breadcrums %}
<li class="breadcrumb-item"><a href="{% url 'gen_list' %}">Listado de Generos</a></li>
<li class="breadcrumb-item">Eliminar</li>
{% endblock breadcrums %} 
    

{% block content %}
<div class="container">
<h1>Eliminar Genero</h1>
<form method="post">
    {% csrf_token %}
    <p>¿Estas seguro de eliminar a <strong>"{{ object }}"</strong>?</p>
    
    <button type="submit" class="btn btn-danger" ><i class="fas fa-trash-alt"></i> Eliminar</button>
    
    <a href="{% url 'gen_list' %}" class="btn btn-light">Cancelar</a> 
</form>

</div>
{% endblock %}

catalog/templates/catalog/genre_create.html
{% extends 'catalog/main.html' %}
{% load bootstrap4 %}


{% block breadcrums %}
<li class="breadcrumb-item"><a href="{% url 'gen_list' %}">Listado de Generos</a></li>
<li class="breadcrumb-item">Agregar Genero </li>
{% endblock breadcrums %}
    
{% block content %}
<div class="container">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <!-- {{ form.as_p }} -->
        <button type="submit" class="btn btn-primary" > Enviar</button>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/index.html
{% extends 'catalog/main.html' %}
{% load static %}

{% block extracss %}
<style>
  .bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
  }

  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 3.5rem;
    }
  }
</style>
{% endblock extracss %}
  
{% block content %}

<div class="container">
    <h1 class="text-center">Librería local</h1>
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'img/carousel1.jpg' %}" alt="">
      </div>
      <div class="carousel-item">
        <img src="{% static 'img/libros.jpg' %}" alt="">
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img"><rect width="100%" height="100%" fill="#777"/></svg>
        <img src="{% static 'img/image.jpeg' %}" alt=""> 
      </div>

    <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

  <div class="container marketing">

    <!-- Three columns of text below the carousel -->
    <div class="row mt-4">
      <div class="col-lg-4">
        <img src="{% static 'img/book.jpeg' %}" class="bd-placeholder-img rounded-circle" width="140" height="140"  preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 140x140"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"/><text x="50%" y="50%" fill="#777" dy=".3em"></text></img>
        <h2>Heading</h2>
        {{ num_instances }}
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <img src="{% static 'img/gold.svg' %}" class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 140x140"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"/><text x="50%" y="50%" fill="#777" dy=".3em"></text></img>
        <h2>Bitcoins</h2>
        <p>Tienes {{ num_visits }} bitcoins para comprar</p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <img src="{% static 'img/SAMURAI.svg' %}"class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 140x140"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"/><text x="50%" y="50%" fill="#777" dy=".3em"></text></img>
        <h2>Autores</h2>
        <p> Tenemos diversos libros de <strong>{{ num_authors }}</strong> autores</p>
      </div><!-- /.col-lg-4 -->
    </div><!-- /.row -->



    <li><strong>Copies:</strong></li>
    <li><strong>Copias de libros disponibles:</strong> {{ num_instances_available }}</li>

  
{% endblock %}